export const CHECK_USER:string ='CHECK_USER'
export const CREATE_ACCOUNT:string ='CREATE_ACCOUNT'
export const RESTORE_PASSWORD:string ='RESTORE_PASSWORD'
export const CREATE_NEW_PASSWORD:string ='CREATE_NEW_PASSWORD'
export const CHECK_IF_USER_OUT:string='CHECK_IF_USER_OUT'
export const CHECK_IF_USER_IN:string='CHECK_IF_USER_IN'
export const SET_LOG_IN:string ='SET_LOG_IN'
export const CHECK_ACCOUNT_NICK_NAME:string = 'CHECK_ACCOUNT_NICK_NAME'